services:

  - type: web
    name: nasa-exoplanet-fullstack
    env: python
    buildCommand: |
      python --version &&
      pip install -r requirements.txt &&
      cd frontend &&
      npm --version &&
      npm install &&
      npm run build &&
      cd ..
    startCommand: python backend/api_predict.py
    autoDeploy: false
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.17.0
